accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup', views.SignupView.as_view(), name='signup'),
    path('profile/edit/<int:pk>', views.ProfileEdit.as_view(), name='profile_edit'),
    path('login', views.Login.as_view(), name='login'),

]

content/urls.py
from django.contrib import admin
from django.urls import path, include
from content.views import  Create, Edit, Delete, Follower, Following
from . import views

app_name='content'
urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:pk>', views.show, name='show'),
    path('comment_btn', views.comment_btn, name='comment_btn'),
    path('good_btn', views.good_btn, name='good_btn'),
    path('create', Create.as_view(), name='create'),
    path('edit/<int:pk>', Edit.as_view(), name='edit'),
    path('delete/<int:pk>', Delete.as_view(), name='delete'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('connection_btn', views.connection_btn, name='connection_btn'),
    path('good', views.good, name='good'),
    path('following/<int:pk>', Following.as_view(), name='following'),
    path('follower/<int:pk>', Follower.as_view(), name='follower'),
    path('find', views.find, name='find'),
]

kuchikuchi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('content/', include('content.urls')),


    # path('logout', views.LogoutView.as_view(), name='logout'),
    # path('password_change', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # path('password_reset', views.PasswordResetView.as_view(), name="password_reset"),
    # path('password_reset/done', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uid64>/<token>', views.PasswordResetConfirmView.as_view(), name='reset'),
    # path('reset/done', views.PasswordResetCompleteView.as_view(), name='reset_done'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models
from accounts.models import CustomUser
from django.core.validators import FileExtensionValidator

import uuid

class Content(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    introduction = models.TextField(max_length=500)
    urls = models.URLField(blank=True)
    upload = models.FileField(
        upload_to='files/',
        validators=[FileExtensionValidator(['mp4', 'webm'])]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title +'by'+ self.owner.username

class Comment(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    comment = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.owner.username + 'comment' + self.content.title


class Good(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)

    def __str__(self):
        return self.owner.username + 'good' + self.content.title

content/forms.py
from django import forms
from .models import Content, Comment
import os.path

VALID_EXTENSIONS = ['.mp4', '.MP4']

class ContentCreate(forms.ModelForm):
    class Meta:
        model = Content
        fields =('title', 'introduction', 'upload', 'urls')
        widgets ={
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'タイトル'
            }),
            'introduction': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': '説明'
            }),
            'upload': forms.ClearableFileInput(attrs={
                'class': 'form-control-file file_preview_form',
                'placeholder': 'アップロードファイル',
            }),
            'urls': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'URL'
            }),
        }
        labels = {
            'title': '',
            'introduction': '',
            'upload': '',
            'urls': '',
        }


class ContentEdit(forms.ModelForm):
    class Meta:
        model = Content
        fields =('title', 'introduction', 'urls')
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'タイトル',
            }),
            'introduction': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': '説明'
            }),
            'urls': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'URL'
            })
        }
        labels = {
            'title': '',
            'introduction': '',
            'urls': '',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =('comment',)
        labels = {
            'comment': "",
        }
        widgets = {
            'comment': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'コメント',
            })
        }

class FindForm(forms.Form):
    find = forms.CharField(
        label='',
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'search',
            'class': 'form-control',
        })
    )

content/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.core import serializers
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q

from accounts.models import CustomUser, Connection
from .models import Content, Comment, Good
from .forms import ContentCreate, ContentEdit, CommentForm, FindForm

def index(request):
    if request.user.is_authenticated:
        connection = Connection.objects.filter(following=request.user)
        followers = [c.follower for c in connection]
        contents = Content.objects.filter(owner__in=followers).order_by('created_at').reverse()
        items = Content.objects.exclude(owner__in=followers).order_by('views_count').reverse()
    else:
        contents = Content.objects.all().order_by('views_count').reverse()
        items = None
    params ={
        'contents': contents,
        'items': items,
    }
    return render(request, 'content/index.html', params)

@login_required(login_url='accounts:login')
def show(request, pk):
    content = get_object_or_404(Content, id=pk)
    comments = Comment.objects.filter(content=content).order_by('created_at').reverse()
    is_good = Good.objects.filter(owner=request.user).filter(content=content)
    #SHOWを訪れた時の視聴回数
    content.views_count +=1
    content.save()
    good_count = Good.objects.filter(content=content).count()
    params ={
        'content': content,
        'form': CommentForm,
        'comments': comments,
        'good_count': good_count,
        'is_good': is_good,
    }
    return render(request, 'content/show.html', params)

def comment_btn(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            content = get_object_or_404(Content, pk=request.POST.get('content_id'))
            owner = request.user
            comment = request.POST.get('comment')
            new = Comment(
                content=content,
                owner=owner,
                comment=comment,
            )
            new.save()
            params = {
                'content_id': content.id,
                'comment': new.comment,
                'username': new.owner.username,
                'avatar_url': new.owner.avatar.url,
            }

        if request.is_ajax():
            return JsonResponse(params)

def good_btn(request):
    if request.method == 'POST':
        content = get_object_or_404(Content, pk=request.POST.get('content_id'))
        owner = request.user
        gooded = False
        good =Good.objects.filter(
            owner=owner,
            content=content,
        )
        if good.exists():
            good.delete()
        else:
            good.create(
                owner=owner,
                content=content,
            )
            gooded = True
        params ={
            'content_id': content.id,
            'gooded': gooded,
            'count': content.good_set.count(),
        }

        if request.is_ajax():
            return JsonResponse(params)

class Create(LoginRequiredMixin, generic.CreateView):
    model = Content
    template_name ='content/create.html'
    form_class = ContentCreate
    success_url = reverse_lazy('content:index')
    def form_valid(self, form):
        content = form.save(commit=False)
        content.owner = self.request.user
        content.save()
        messages.success(self.request, '投稿完了！！')
        #このform_validがsuccess_urlのURLを指している。
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request, '投稿できませんでした。')
        return super().form_invalid(form)

class Edit(LoginRequiredMixin, generic.UpdateView):
    model = Content
    template_name ='content/edit.html'
    form_class = ContentEdit

    # success_url と get_success_urlの違い
    # ↑静的なページ　　　↑動的なページ　遷移のちがいである。
    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'content:show',
            kwargs={'pk' :self.kwargs['pk']}
        )

    # ログインしているユーザが作ったもでなければアクセス不可
    def get_queryset(self):
        # このビューで生成されるベースとなるクエリセットを取得
        base_qs = super(Edit, self).get_queryset()
        # さらにユーザIDで絞った結果を返す。(存在しないので404が返る)
        # 条件分岐してエラーページを出しても可
        return base_qs.filter(owner=self.request.user)

    def form_valid(self, form):
        messages.success(self.request, '投稿編集完了!!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, '投稿編集できませんでした。')
        return super().form_invalid(form)


class Delete(LoginRequiredMixin, generic.DeleteView):
    model = Content
    template_name ='content/delete.html'
    success_url = reverse_lazy('content:index')

    def get_queryset(self):
        # このビューで生成されるベースとなるクエリセットを取得
        base_qs = super(Delete, self).get_queryset()
        # さらにユーザIDで絞った結果を返す。(存在しないので404が返る)
        # 条件分岐してエラーページを出しても可
        return base_qs.filter(owner=self.request.user)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '投稿を削除しました。')
        return super().delete(request, *args, **kwargs)


@login_required(login_url='accounts:login')
def profile(request, pk):
    contents = Content.objects.filter(owner_id=pk)
    user = get_object_or_404(CustomUser, id=pk)
    following_count = Connection.objects.filter(following_id=pk).count()
    follower_count = Connection.objects.filter(follower_id=pk).count()

    #自分がこのユーザーをfollowしているのか否かを調べる。
    check = Connection.objects.filter(follower=user, following=request.user)
    params = {
        'contents': contents,
        'user': user,
        'following_count': following_count,
        'follower_count': follower_count,
        'check': check,
    }
    return render(request, 'content/profile.html', params)

def connection_btn(request):
    if request.method == 'POST':
        follower = get_object_or_404(CustomUser, pk=request.POST.get('user_id'))
        following = request.user
        checked = False
        connection = Connection.objects.filter(
            following=following,
            follower=follower,
        )
        if connection.exists():
            connection.delete()
        else:
            connection.create(
                following=following,
                follower=follower,
            )
            checked = True

        params = {
            'checked': checked,
            'follower_count': Connection.objects.filter(follower=follower).count(),
        }

        if request.is_ajax():
            return JsonResponse(params)


@login_required(login_url='accounts:login')
def good(request):
    goods = Good.objects.filter(owner=request.user)

    return render(request, 'content/good.html', {'goods': goods})

class Following(LoginRequiredMixin, generic.TemplateView):
    template_name='content/following.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followings'] = Connection.objects.filter(following_id=self.kwargs['pk'])
        context['person'] = get_object_or_404(CustomUser, id=self.kwargs['pk'])
        return context

class Follower(LoginRequiredMixin, generic.TemplateView):
    template_name='content/follower.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followers'] = Connection.objects.filter(follower_id=self.kwargs['pk'])
        context['person'] = get_object_or_404(CustomUser, id=self.kwargs['pk'])
        return context

def find(request):
    if request.method == 'POST':
        form = FindForm(request.POST)
        find = request.POST['find']
        content = Content.objects.filter(
            Q(title__contains=find)|
            Q(introduction__contains=find)|
            Q(owner__username__contains=find)
            ).order_by('views_count').reverse()
        msg = '検索結果' + str(content.count()) +'件'
    else:
        msg ='' 
        content = Content.objects.all().order_by('views_count').reverse()
        form = FindForm()
    params = {
        'msg': msg,
        'form': form,
        'contents': content,
    }
    return render(request, 'content/find.html', params)

templates/content/comment.html
<h3>KuchiKuchi</h3>
<div id="comment_add">

</div>

{% for comment in comments %}
    <div class="shadow-sm rounded-pill comment_area">
        <diV class="flex-column comment_box">
            <div id="comment_user_username">
                <img class="my_img"
                     src="{{ comment.owner.avatar.url }}">
                {{ comment.owner.username }}
            </div>
            <div class="text-break comment_detail" >
                {{ comment.comment }}
            </div>
        </diV>
    </div>
{% endfor %}
<div class="fixed-bottom comment_form_area">
    <form method="post" action="{% url 'content:comment_btn' %}" id="comment_btn_form" class="{{ content.pk }}">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="comment_btn">
            <i class="fas fa-lg fa-comment comment_icon"></i>
        </button>
    </form>
</div>

templates/content/create.html
{% extends 'layout.html' %}
{% load static %}
{% block extra_js %}
    <script src="{% static 'js/file_preview.js' %}"></script>
{% endblock %}
{% block content %}
    <form class="common_form" method="POST" enctype="multipart/form-data">
        <video id="file_preview"
            playsinline
            autoplay
            muted>
        </video>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn submit_btn" type="submit">
            アップロード
        </button>
    </form>
{% endblock %}

templates/content/delete.html
{% extends 'layout.html' %}
{% block title %}Delete{% endblock %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <p>本当に削除しますか？</p>
        <button class="btn submit_btn" type="submit">
            削除
        </button>
    </form>
    <a href="{% url 'content:show' object.id %}">
        キャンセル
    </a>
{% endblock %}

templates/content/edit.html
{% extends 'layout.html' %}
{% block title %}Edit{% endblock %}
{% block content %}
    <form method="POST" class="common_form">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn submit_btn" type="submit">
            編集
        </button>
    </form>
    <a href="{% url 'content:delete' object.id %}">
        削除
    </a>
{% endblock %}

templates/content/find.html
{% extends 'layout.html' %}
{% block content %}
<p>{{msg}}</p>
<form action="{% url 'content:find' %}" method="POST">
    {% csrf_token %}
    <div class="d-flex justify-content-center">
        {{ form.as_p }}
        <button type="submit" class="btn find_btn" >
            <i class="fas fa-lg fa-search submit_icon"></i>
        </button>
    </div>
</form>
{% include 'content/video.html' %}
{% endblock %}

templates/content/follower.html
{% extends 'layout.html' %}
{% block content %}
{% include 'content/my_profile_layout.html' %}
    {% for follower in followers %}
        <div class="shadow-sm rounded connection_area">
            <table>
                <tr>
                    <td>
                        <img class="my_img"
                             src="{{ follower.following.avatar.url }}">
                    </td>
                    <td>
                        <a href="{% url 'content:profile' follower.following.pk %}">
                            {{ follower.following.username}}
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    {% endfor %}
{% endblock %}

templates/content/following.html
{% extends 'layout.html' %}
{% block content %}
{% include 'content/my_profile_layout.html' %}
    {% for following in followings%}
        <div class="shadow-sm rounded connection_area" >
            <table>
                <tr>
                    <td>
                        <img class="my_img"
                             src="{{ following.follower.avatar.url }}">
                    </td>
                    <td>
                        <a href="{% url 'content:profile' following.follower.pk %}">
                            {{ following.follower.username}}
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    {% endfor %}
{% endblock %}

templates/content/good.html
{% extends 'layout.html' %}
{% block content %}
    {% for good in goods %}
        <div class="shadow-sm rounded content_area">
            <div class="d-flex flex-row">
                <img class="my_img"
                     src="{{ good.content.owner.avatar.url }}">
                <a href="{% url 'content:profile' good.content.owner.pk %}">
                    {{ good.content.owner.username}}
                </a>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="embed-responsive embed-responsive-21by9">
                        <a href="{% url 'content:show' good.content.pk %}">
                            <video-js class="embed-responsive-item vide-js"
                               data-setup='{ "autoplay": true}'
                               controlsList="nodownload"
                               oncontextmenu="return false;"
                               playsinline
                               loop
                               muted>
                                <source src="{{ good.content.upload.url }}" type="video/mp4">
                            </video-js>
                        </a>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="text-break">
                        <a class="show_title" href="{% url 'content:show' good.content.pk %}">
                            {{ good.content.title }}
                        </a>
                    </div>
                    <div class="text-break">
                        {{ good.content.introduction | truncatechars:100}}
                    </div>
                    <div class="index_created_at">
                        <p class="created_at">
                            {{ good.content.created_at }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/content/good_form.html
<diV class="d-flex flex-row">
    <div>
        <form class="good_btn_form" id="{{ content.pk }}" action="{% url 'content:good_btn' %}" method="POST">
            {% csrf_token %}
            {% if is_good %}
                <button type="submit" class="good_btn">
                    <i class="fas fa-lg fa-heart submit_icon"></i>
                </button>
            {% else %}
                <button type="submit" class="good_btn" name="{{ content.pk }}">
                    <i class="far fa-lg fa-heart submit_icon"></i>
                </button>
            {% endif %}
        </form>
    </div>
    <div id="good_count">
        {{ good_count }}
    </div>
</diV>

templates/content/index.html
{% extends 'layout.html' %}
{% block content %}
{% include 'content/video.html' %}
    {% for item in items %}
    <div class="shadow-sm rounded content_area">
        <div class="d-flex flex-row">
            <img class="my_img"
                 src="{{ item.owner.avatar.url }}">
            <a href="{% url 'content:profile' item.owner.pk %}">
                {{ item.owner.username}}
            </a>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="embed-responsive embed-responsive-21by9">
                <a href="{% url 'content:show' item.pk %}">
                   <video-js class="embed-responsive-item vjs-big-play-centered"
                          playsinline
                          data-setup={}
                          controlsList="nodownload"
                          oncontextmenu="return false;">
                        <source src="{{ item.upload.url }}" type="video/mp4">
                        <source src="{{ item.upload.url }}" type="video/webm" >
                    </video-js>
                </a>
                </div>
            </div>
            <div class="col-md-7">
                <div>
                    <div class="text-break">
                        <a class="show_title" href="{% url 'content:show' item.pk %}">
                            {{ item.title }}
                        </a>
                    </div>
                    <div class="text-break">
                        <p>
                            {{ item.introduction | truncatechars:100 }}
                        </p>
                    </div>
                    <div class="index_created_at">
                        <p class="created_at">
                            {{ item.created_at }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

templates/content/my_profile_layout.html
<div class="d-flex flex-row">
    <div>
        <img class="my_profile_img"
             src="{{ person.avatar.url }}">
    </div>
    <div class="my_profile_username_area">
        <a href="{% url 'content:profile' person.pk%}">
        {{ person.username }}
        </a>
    </div>
</div>

templates/content/profile.html
{% extends 'layout.html' %}
{% load static %}
{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/connection.js' %}"></script>
{% endblock %}

{% block content %}
<div class="d-flex flex-row">
    <div>
        <img class="my_profile_img" src="{{ user.avatar.url }}">
    </div>
    <div class="my_profile_username_area">
        <a href="{% url 'content:profile' user.pk %}">
            {{ user.username }}
        </a>
    </div>
    {% if user == request.user %}
        <div class="dropdown_area">
            <div class="dropdown">
                <button class="btn dropdown-toggle-split" type="button" id="dropdown1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-lg fa-cogs submit_icon"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdown1">
                    <a class="dropdown-item" href="{% url 'accounts:profile_edit' request.user.id %}">
                        ユーザー編集
                    </a>
                    <a class="dropdown-item" href="/accounts/logout">
                        ログアウト
                    </a>
                </div>
            </div>
        </div>
    {% endif %}
</div>
    <div>
    <div class="d-flex flex-row">
        <ul class="follow_and_follower_count" >
            <a href="{% url 'content:following' user.pk %}">
                <li>
                    follow
                </li>
                <li class="text-center">
                    {{ following_count }}
                </li>
            </a>
        </ul>
        <ul class="follow_and_follower_count">
            <a href="{% url 'content:follower' user.pk %}">
                <li>
                    follower
                </li>
                <li class="text-center" id="follower_count">
                    {{ follower_count }}
                </li>
            </a>
        </ul>
    </div>
</div>
<div>
    {% if request.user != user %}
    <form class="connection_btn_form" id="{{ user.pk }}"  action="{% url 'content:connection_btn' %}" method="POST">
        {% csrf_token %}
        <button class="btn submit_btn" id="check_connection" name="{{ user.pk }}" type="submit">
            {% if check %}
                unfollow
            {% else %}
                follow
            {% endif %}
        </button>
    </form>
    {% endif %}
</div>
{% include 'content/video.html' %}
{% endblock %}

templates/content/show.html
{% extends 'layout.html' %}
{% load static %}
{% block extra_js %}
    <script src="{% static 'js/good_btn.js' %}"></script>
    <script src="{% static 'js/comment_btn.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="shadow-sm rounded show_area">
        <div class="d-flex flex-row">
            <img class="my_img"
                 src="{{ content.owner.avatar.url }}">
            <a href="{% url 'content:profile' content.owner.pk %}">
                {{ content.owner.username }}
            </a>
        </div>
        <div>
            <div>
                <div class="embed-responsive embed-responsive-21by9">
                    <video-js class="embed-responsive-item vjs-big-play-centered"
                           data-setup='{ "playbackRates": [1, 1.5, 2] }'
                           controls
                           controlsList="nodownload"
                           oncontextmenu="return false;"
                           playsinline>
                        <source src="{{ content.upload.url }}" type="video/mp4">
                        <source src="{{ content.upload.url }}" type="video/webm">
                    </video-js>
                </div>
            </div>
            <div class="show_info_area">
                <div class="count">
                    {% include 'content/good_form.html' %}
                    <div class="d-flex flex-row">
                        <div class="views_count_icon">
                            <i class="fas fa-lg fa-eye submit_icon"></i>
                        </div>
                        <div>
                            {{ content.views_count }}
                        </div>
                    </div>
                </div>
                <div class="text-break">
                    <h5 class="show_title">
                        {{ content.title }}
                    </h5>
                </div>
                <div class="text-break">
                    <p>
                        {{ content.introduction| linebreaksbr }}
                    </p>
                </div>
                <div class="right_to">
                    <button class="btn submit_btn">
                        <a href="{{ content.urls }}">
                            URL
                        </a>
                    </button>
                </div>
                <div class="right_to">
                    <p>
                        {{ content.created_at }}
                    </p>
                </div>
                <div class="right_to">
                    {% if content.owner == request.user %}
                    <a class="a_edit" href="{% url 'content:edit' content.pk%}">
                        edit
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% include 'content/comment.html' %}

{% endblock %}

templates/content/video.html
{% for content in contents %}

    <div class="shadow-sm rounded content_area">
        <div class="d-flex flex-row">
            <img class="my_img"
                 src="{{ content.owner.avatar.url }}">
            <a href="{% url 'content:profile' content.owner.pk %}">
                {{ content.owner.username }}
            </a>
        </div>
        <div class="row">
            <div class="col-md-5">
            <a href="{% url 'content:show' content.pk %}">
                <div class="embed-responsive embed-responsive-21by9">
                    <video-js class="embed-responsive-item"
                           data-setup={}
                           controlsList="nodownload"
                           oncontextmenu="return false;"
                           playsinline>
                        <source src="{{ content.upload.url }}" type="video/mp4">
                        <source src="{{ content.upload.url }}" type="video/webm">
                    </video-js>
                </div>
            </a>
            </div>
            <div class="col-md-7">
                <div class="text-break">
                    <a class="show_title" href="{% url 'content:show' content.pk %}">
                        {{ content.title }}
                    </a>
                </div>
                <div class="text-break">
                    {{ content.introduction | truncatechars:100 }}
                </div>
                <div class="index_created_at">
                    <p class="created_at">
                        {{ content.created_at }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endfor %}