accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup', views.SignupView.as_view(), name='signup'),
    path('profile/edit/<int:pk>', views.ProfileEdit.as_view(), name='profile_edit'),
    path('login', views.Login.as_view(), name='login'),

]

content/urls.py
from django.contrib import admin
from django.urls import path, include
from content.views import  Create, Edit, Delete, Follower, Following
from . import views

app_name='content'
urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:pk>', views.show, name='show'),
    path('comment_btn', views.comment_btn, name='comment_btn'),
    path('good_btn', views.good_btn, name='good_btn'),
    path('create', Create.as_view(), name='create'),
    path('edit/<int:pk>', Edit.as_view(), name='edit'),
    path('delete/<int:pk>', Delete.as_view(), name='delete'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('connection_btn', views.connection_btn, name='connection_btn'),
    path('good', views.good, name='good'),
    path('following/<int:pk>', Following.as_view(), name='following'),
    path('follower/<int:pk>', Follower.as_view(), name='follower'),
    path('find', views.find, name='find'),
]

kuchikuchi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('content/', include('content.urls')),


    # path('logout', views.LogoutView.as_view(), name='logout'),
    # path('password_change', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # path('password_reset', views.PasswordResetView.as_view(), name="password_reset"),
    # path('password_reset/done', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uid64>/<token>', views.PasswordResetConfirmView.as_view(), name='reset'),
    # path('reset/done', views.PasswordResetCompleteView.as_view(), name='reset_done'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout.html
{% load static %}
<!DOCTYPE html>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=True %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--jQueryファイル-->
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<!--    <script src="https://code.jquery.com/jquery-3.6.0.js"-->
<!--        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="-->
<!--        crossorigin="anonymous">-->
<!--    </script>-->

    <!--video-jsファイル-->
    <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
    <script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>

    <!--    fontawesomeファイル-->
    <script src="https://kit.fontawesome.com/f7264e661c.js" crossorigin="anonymous"></script>

    <!--外部のstaticファイル読み込み-->
<!--    <script src="{% static 'js/main.js' %}"></script>-->

<!--    AJAX cookieからcsrftokenを取得して、x-csrftokenにセットして送信する。-->
    <script src="{% static 'js/ajax_setup.js' %}"></script>

<!--    その他ファイルのjsファイル-->
    {% block extra_js %}{% endblock %}

<!--    cssファイル-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="container">
    <header class="fixed-top">
        <nav class="navbar navbar-light">
            <a class='navbar-brand' href="{% url 'content:index' %}" >
                KuchiKuchi
            </a>
            <a href="{% url 'content:create' %}">
                <i class="fas fa-lg fa-plus-square header_icon"></i>
            </a>
            <a href="{% url 'content:good' %}">
                <i class="fas fa-lg fa-heart header_icon"></i>
            </a>
            <a href="{% url 'content:find' %}">
                <i class="fas fa-lg fa-search header_icon"></i>
            </a>
            {% if user.is_authenticated %}
                <a href="{% url 'content:profile' request.user.pk %}">
                    <img class="my_img"
                         src="{{ request.user.avatar.url }}">
                </a>
            {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
            {% endif %}
        </nav>
    </header>
    <div class="main">
        {% block content %}{% endblock %}
    </div>
</body>
</html>